---
platform: linux
image_resource: 
  type: docker-image
  source:
    repository: concourse/static-golang

inputs:
- name: datadog-event-resource
  path: gopath/src/github.com/concourse/datadog-event-resource

outputs:
- name: built-resource

run:
  path: gopath/src/github.com/concourse/datadog-event-resource/scripts/ci
